const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.EightDir,
		C3.Behaviors.solid,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Behaviors.EightDir.Acts.SimulateControl,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.PickChildren
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{Platform: 0},
	{Timer: 0},
	{Shooter: 0},
	{Bullet: 0},
	{Num: 0},
	{Block: 0},
	{txtBlock: 0},
	{txtScore: 0},
	{wall: 0},
	{"8Direction": 0},
	{Solid: 0},
	{FBlock: 0},
	{StartX: 0},
	{GameOver: 0},
	{score: 0},
	{vNum: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	Shooter: class extends self.ISpriteInstance {},
	Bullet: class extends self.ISpriteInstance {},
	Block: class extends self.ISpriteInstance {},
	txtBlock: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {},
	wall: class extends self.ITiledBackgroundInstance {},
	FBlock: class extends self.ISpriteInstance {}
}